#### 1. Import the numpy package under the name `np` (★☆☆)

In [8]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [9]:
m = np.zeros(10)
m

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
m[4] = 1
m

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 7. Create a 3x3 identity matrix (★☆☆)

In [14]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [15]:
np.random.random((3,3))

array([[1.33321323e-01, 3.52963184e-01, 6.58699235e-01],
       [4.87650942e-01, 1.82204330e-01, 9.02832718e-04],
       [9.41483302e-01, 2.04773737e-01, 9.39474785e-01]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
a_9 = np.random.random((10,10))
print(np.min(a_9))
print(np.max(a_9))

0.008287391919775788
0.9991733529815291


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
np.mean(np.random.random(30))

0.4722425274757079

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
b = np.diag(1+ np.arange(4),k=-1)
print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)

In [19]:
a_12 = np.random.random((5,5))
a_12_norm = (a_12 - np.mean(a_12)) / np.std(a_12)
a_12_norm

array([[ 0.45762325, -0.32358053,  0.03003083, -0.30575314,  0.59511528],
       [ 0.15860134, -1.07866617, -1.05347695,  1.712753  , -0.42716893],
       [-0.32074612, -0.1686491 ,  0.22599552,  1.36751058, -0.04692081],
       [-0.944924  ,  1.62337297, -0.59988757, -1.71360826, -1.26563342],
       [ 1.76227274,  1.18464839, -0.91582295, -1.19985093,  1.24676498]])

#### 13. How to find common values between two arrays? (★☆☆)

In [22]:
a_13_a = np.arange(10, 16)
a_13_b = np.arange(11, 17)
a_13 = np.intersect1d(a_13_a, a_13_b)
a_13

array([11, 12, 13, 14, 15])

#### 14. Create a random vector of size 10 and sort it (★★☆)

In [25]:
a_14 = np.random.random(10)
a_14_sorted = np.sort(a_14)
a_14_sorted

array([0.07889058, 0.19095734, 0.19610931, 0.31935676, 0.42002962,
       0.62388972, 0.62604321, 0.7316434 , 0.73164764, 0.85655787])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [33]:
a_15 = np.random.random(10)
a_15_mod = [0 if i == ny.max(a_15) else i for i in a_15]
print(a_15)
print(a_15_mod)

[0.21348816 0.77714874 0.03163452 0.95928965 0.68220665 0.66018199
 0.00690156 0.48918447 0.13262457 0.56073276]
[0.21348816344918908, 0.7771487399424815, 0.031634517620975244, 0, 0.6822066526270726, 0.6601819940561529, 0.006901558447439116, 0.48918446694187456, 0.13262457456115773, 0.5607327554660682]


#### 16. Subtract the mean of each row of a matrix (★★☆)

In [41]:
a_16 = np.random.random((5,5))
a_16_mean = np.tile(np.mean(a_16, axis = 1, keepdims = True), np.shape(a_16)[1])
a_16_result = a_16 - a_16_mean
a_16_result

array([[-0.03160561,  0.03145772, -0.13587179,  0.3972873 , -0.26126763],
       [-0.16079554, -0.02968359, -0.05334714, -0.1111954 ,  0.35502167],
       [-0.31997266, -0.01626011, -0.00069341,  0.03585873,  0.30106745],
       [ 0.06405712,  0.23427658,  0.00933722, -0.06338404, -0.24428688],
       [ 0.31659488, -0.33398322,  0.03849462,  0.16448795, -0.18559424]])

In [44]:
# Alternative
a_16 = np.random.random((5,5))
a_16_result = a_16 - np.mean(a_16, axis = 1, keepdims = True)
a_16_result

array([[-0.03160561,  0.03145772, -0.13587179,  0.3972873 , -0.26126763],
       [-0.16079554, -0.02968359, -0.05334714, -0.1111954 ,  0.35502167],
       [-0.31997266, -0.01626011, -0.00069341,  0.03585873,  0.30106745],
       [ 0.06405712,  0.23427658,  0.00933722, -0.06338404, -0.24428688],
       [ 0.31659488, -0.33398322,  0.03849462,  0.16448795, -0.18559424]])

#### 17. How to get the n-largest values of an array (★★★)

In [51]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
np.argsort(Z)


array([3974, 3396,  650, ..., 5132, 6964, 8302])

In [52]:
Z

array([4492,  946, 4383, ..., 6943, 2280, 8853])

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 